apiVersion: apiextensions.crossplane.io/v2  # fixed value
kind: CompositeResourceDefinition # fixed value
metadata:
  name: namespaces.soprasteria.local # combination of the type of resource and group, which is usually an fqdn
spec:
  scope: Cluster  # default value in v2
  group: soprasteria.local  # chosen group which is usally an fqdn
  names: 
    kind: XNamespace   # chosen value but should start with capital X and the next letter is also a capital
    plural: namespaces
  versions:
  - name: v1alpha1   # selected but default value
    served: true     # it's operational
    referenceable: true # xr's can reference it
    schema:  # fixed value
      openAPIV3Schema:   # fixed value
        type: object # fixed value
        properties: # fixed value
          spec:  # fixed value
            type: object # fixed value
            properties: # fixed value 
              name:  # chosen, belongs to namespace k8s resource
                type: string  # chosen, belongs to namespace k8s resource
              labels: # chosen, belongs to namespace k8s resource
                type: object # chosen, belongs to namespace k8s resource
                additionalProperties: # chosen, belongs to namespace k8s resource
                  type: string # chosen, belongs to namespace k8s resource
              annotations: # chosen, belongs to namespace k8s resource
                type: object # chosen, belongs to namespace k8s resource
                additionalProperties: # chosen, belongs to namespace k8s resource
                  type: string   # chosen, belongs to namespace k8s resource  
            required: 
              - name   # required field that the xr should provide     
          status:
            type: object
            properties:
              ready:
                type: boolean
              observedNamespace:
                type: string  